name: 'Judge Action'
description: 'Runs judge tests against a student Docker image'

inputs:
  image:
    description: 'Student Docker image name'
    required: true
  judge_image:
    description: 'Judge Docker image'
    required: false
    default: 'knoker123/my-judge:v1'
  assignment_type:
    description: 'basic или advanced'
    required: true
    default: 'basic'

runs:
  using: 'composite'
  steps:
    - name: Set environment variables
      shell: bash
      run: |
        echo "IMAGE_SOLUTION=${{ inputs.image }}" >> $GITHUB_ENV
        echo "IMAGE_JUDGE=${{ inputs.judge_image }}" >> $GITHUB_ENV
        echo "ASSIGNMENT_TYPE=${{ inputs.assignment_type }}" >> $GITHUB_ENV

    - name: Execute Judge Tests
      shell: bash
      run: |
        docker compose -f ${{ github.action_path }}/docker-compose.yml up \
          --abort-on-container-exit \
          --exit-code-from judge

    - name: Cleanup containers
      if: always()
      shell: bash
      run: |
        docker compose -f ${{ github.action_path }}/docker-compose.yml down -v --remove-orphans