name: 'Judge Action'

inputs:
  image:
    description: 'Student Docker image name'
    required: true
  judge_image:
    description: 'Judge Docker image'
    required: false
    default: 'knoker123/my-judge:v1'


runs:
  using: 'composite'
  steps:
    - name: Run judge
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/run.sh
        ${{ github.action_path }}/run.sh
      env:
        IMAGE_SOLUTION: ${{ inputs.image }}
        IMAGE_JUDGE: ${{ inputs.judge_image }}

    - name: Show logs on failure
      if: failure()
      shell: bash
      run: |
        echo "===== student-app logs ====="
        docker compose -f /tmp/judge-compose.yml logs student-app || true
        echo "===== db logs ====="
        docker compose -f /tmp/judge-compose.yml logs db || true
        echo "===== redis logs ====="
        docker compose -f /tmp/judge-compose.yml logs redis || true